### ISSUE TITLE
Using get-job endpoint instead of list-jobs repeatedly

### ISSUE THREAD

**Issue by log101** [duckbytes/amplify-build-status#1]
Hi, in order to get status of the job `list-jobs` endpoint is called repeatedly here: https://github.com/duckbytes/amplify-build-status/blob/08a6b723b23bf0ad186ef604ed3e29aae8bacc21/entrypoint.sh#L46

IMHO It might be more effective to get the job id from `list-jobs` first and then call the `get-job` for the status. So that you won't have to deal with the list again.

**Comment by duckbytes** [comment]
That makes sense to me. Do you want to make a pull request or shall I look into it when I next have time?

**Comment by log101** [comment]
I'd love to contribute, I'm working on it right now and probably will be sending a pr in a few days.

**Comment by duckbytes** [comment]
hey @log101 are you still interested in making a pull request? I might do some more work on this, but don't want to if it conflicts with any work you'd like to merge.

**Comment by log101** [comment]
I'm still interested, I actually have a working implementation. But code is bit messy, I'll send the PR, you can merge it if you like. You can only use it as a sample code, that's completely OK. So feel free to edit or reject my PR.

**Comment by log101** [comment]
Nevermind, my PR would only add a ability to log the build status that's all, it doesn't solve the problem I mentioned at the beginning. So I'm closing the issue now. But I'd to love contribute for the future fixes or features.
